export const HOME = '/'
export const LOGIN = '/login'
export const UPDATE_PROFILE = '/update-profile'
export const NOT_FOUND = '/not-found'
export const POST_JOB = '/post-job'
export const FIND_JOB = '/find-job'
export const DASHBOARD = '/dashboard'